### ISSUE TITLE
Neptune bindings support

### ISSUE THREAD

**Issue by sufiand** [schwartzmx/gremtune#6]
the Readme says that the reason why this was forked from gremgo was to handle missing features in neptune like bindings. But I still see the method ExecuteWithBindings and it does not work as expected. The passed bindings do not get substituted in the executed query. So, how exactly is this different from gremgo?

**Comment by schwartzmx** [comment]
It was forked because Neptune does _not_ (or did not when initially forked) support bindings and gremgo _only_ supported executing with bindings.  There's also been numerous other changes since the initial fork,  especially involving the Response struct.

From the readme (emphasis mine)
>Modifications were made to gremgo in order to "support" AWS Neptune's lack of Gremlin-specific features, like **no** support query bindings among others.

You can see this still listed here https://docs.aws.amazon.com/neptune/latest/userguide/access-graph-gremlin-differences.html
>Variables
>Neptune does not support Gremlin variables and does not support the bindings property.

Also this originally was **not** intended to be a Neptune specific client (even though it can be inferred from the new name),  so the ExecuteWithBindings function was born from the old Execute() (from gremgo) to allow users to still use bindings supported GraphDBs

**Comment by sufiand** [comment]
Fair enough and appreciate the response. 

Given that neptune does not support bindings and this client is specifically for neptune, it would make sense to remove the method ExecuteWithBindings altogether to avoid such confusion.
